//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coders
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConditionedHint
    {
        public int Id { get; set; }
        public Nullable<int> Fulfilled { get; set; }
        public Nullable<int> Head { get; set; }
        public Nullable<int> Child { get; set; }
    
        public virtual Landmark Landmark { get; set; }
        public virtual Landmark Landmark1 { get; set; }
    }
}
