//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coders
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rout()
        {
            this.UserRouts = new HashSet<UserRout>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LandmarkParent_Id { get; set; }
        public Nullable<int> LandmarkChild_Id { get; set; }
        public Nullable<int> Competition_Id { get; set; }
    
        public virtual Competition Competition { get; set; }
        public virtual Landmark Landmark { get; set; }
        public virtual Landmark Landmark1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRout> UserRouts { get; set; }
    }
}
