//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Coders
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRating
    {
        public int Id { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> NewLandmarksId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual NewLandmark NewLandmark { get; set; }
        public virtual User User { get; set; }
    }
}
